#! /usr/bin/bash

GZDOOMR_CONFIG="${HOME}/.config/gzdoom"
GZDOOMR_BIN=/usr/bin/gzdoomrun
GZDOOMR_GUI_1312_BIN=/usr/bin/gzdoomrungui-1-3-12
GZDOOMR_GUI_BIN=/usr/bin/gzdoomrungui
GZDOOMR_CUSTOM_DIR="${GZDOOMR_CONFIG}/custom"
GZDOOMR_CUSTOM="${GZDOOMR_CUSTOM_DIR}.py"
GZDOOMR_DESKTOP=/usr/share/applications/gzdoomrun.desktop
GZDOOMR_STEAM_BANNER="${GZDOOMR_CONFIG}/banner.jpg"
GZDOOMR_STEAM_LOGO="${GZDOOMR_CONFIG}/logo.png"
GZDOOMR_STEAM_ARTWORK="${GZDOOMR_CONFIG}/artwork.png"

function install-gzdoom () {
    printf "Installing GZDoom Run ... \n\n"

    sudo touch $GZDOOMR_BIN
    sudo cp ./gzdoomrun-main.py $GZDOOMR_BIN
    sudo cp ./gzdoomrun.py $GZDOOMR_BIN.py
    
    raco pkg install gui-easy
    raco exe ./gzdoomrungui.rkt
    sudo cp ./gzdoomrungui $GZDOOMR_GUI_1312_BIN
    rm ./gzdoomrungui
    sudo cp ./gzdoomrungui.py $GZDOOMR_GUI_BIN
    
    cp ./artwork.png $GZDOOMR_STEAM_ARTWORK
    cp ./logo.png $GZDOOMR_STEAM_LOGO
    cp ./banner.jpg $GZDOOMR_STEAM_BANNER
    cp ./custom.py $GZDOOMR_CUSTOM
    cp -r ./custom $GZDOOMR_CUSTOM_DIR
    
    sudo cp ./gzdoomrun.desktop $GZDOOMR_DESKTOP

    RET=$?
    printf "\nDone.\n"
    return $RET
}

function check-done () {
    if [ $1 -eq 0 ]
    then
        printf "\nDone.\n"
    else
        printf "\nCould not install %s!\n" $PKG_NAME
        exit 1
    fi
}

function install-module () {
    PKG_NAME=$1
    cd $PKG_NAME
    
    if [ $? -eq 1 ]
    then 
        unzip "./${PKG_NAME}.pkz"
        check-done $? $PKG_NAME
        cd $PKG_NAME
        check-done $? $PKG_NAME
    fi
    
    ./install
    RET=$?
    cd ..

    return $RET
}

alias install-brutal="install-module brutal"
alias install-sigil="install-module sigil"

if [ $# -eq 1 ]
then
    if [ $1 = gzdoom ]
    then
        install-gzdoom
    elif [ $1 = brutal ]
    then
        install-brutal
    elif [ $1 = sigil ]
    then 
        install-sigil
    elif [ $1 = all ]
    then 
        install-gzdoom
        install-brutal
        install-sigil
    else
        install-module $1
        
        if [ $? -eq 1 ]
        then
            printf "\nInvalid argument '%s'\n" $ARG 
            exit 1
        fi
    fi
else 
    install-gzdoom
fi

exit $?

