#! /usr/bin/bash

GZDOOMR_CONFIG="${HOME}/.config/gzdoom"
GZDOOMR_BIN=/usr/bin/gzdoomrun
GZDOOMR_GUI_1312_BIN=/usr/bin/gzdoomrun-1-3-12
GZDOOMR_BIN=/usr/bin/gzdoomrun
GZDOOMR_LIB="${GZDOOMR_CONFIG}/gzdoomrunlib"
GZDOOMR_CUSTOM_DIR="${GZDOOMR_CONFIG}/custom"
GZDOOMR_CUSTOM="${GZDOOMR_CUSTOM_DIR}.py"
GZDOOMR_DESKTOP=/usr/share/applications/gzdoomrun.desktop
GZDOOMR_STEAM_BANNER="${GZDOOMR_CONFIG}/banner.jpg"
GZDOOMR_STEAM_LOGO="${GZDOOMR_CONFIG}/logo.png"
GZDOOMR_STEAM_ARTWORK="${GZDOOMR_CONFIG}/artwork.png"
GZDOOMR_MODCACHE="${GZDOOMR_CONFIG}/modcache.json"

function uninstall-gzdoom () {
    printf "uninstalling GZDoom Run ... \n\n"
    
    sudo rm -r $GZDOOMR_LIB
    sudo rm $GZDOOMR_BIN
    
    rm $GZDOOMR_STEAM_ARTWORK
    rm $GZDOOMR_STEAM_LOGO
    rm $GZDOOMR_STEAM_BANNER
    rm -r $GZDOOMR_CUSTOM_DIR
    
    sudo rm $GZDOOMR_DESKTOP

    RET=$?
    printf "\nDone.\n"
    return $RET
}

function check-done () {
    if [ $1 -eq 0 ]
    then
        printf "\nDone.\n"
    else
        printf "\nCould not uninstall %s!\n" $2
        exit 1
    fi
}

function uninstall-module () {
    PKG_NAME=$1
    cd $PKG_NAME
    check-done $? $PKG_NAME
    ./uninstall
    RET=$?
    cd ..

    return $RET
}

if [ $# -eq 1 ]
then
    if [ $1 = gzdoom ]
    then
        uninstall-gzdoom
    elif [ $1 = brutal ]
    then
        uninstall-module brutal
    elif [ $1 = sigil ]
    then 
        uninstall-module sigil
    elif [ $1 = all ]
    then 
        uninstall-gzdoom
        uninstall-module brutal
        uninstall-module sigil
    else
        uninstall-module $1

        if [ $? -eq 1 ]
        then
            printf "\nInvalid argument '%s'\n" $ARG 
            exit 1
        fi
    fi
else 
    uninstall-gzdoom
fi

exit $?