#! /usr/bin/bash

GZDOOMR_CONFIG="${HOME}/.config/gzdoom"
BRUTAL_DOOM_CONFIG="${GZDOOMR_CONFIG}/brutalv21"
BRUTAL_DOOM_STEAM_BANNER="${BRUTAL_DOOM_CONFIG}/banner.jpg"
BRUTAL_DOOM_STEAM_LOGO="${BRUTAL_DOOM_CONFIG}/logo.png"
BRUTAL_DOOM_ICON=/usr/share/icons/brutal-doom.png
BRUTAL_DOOM_DESKTOP=/usr/share/applications/brutal-doom.desktop

printf "Installing Brutal Doom ... \n\n"

gzdoom-run install brutalv21.pk3
sudo cp ./icon.png $BRUTAL_DOOM_ICON
sudo cp ./brutal-doom.desktop $BRUTAL_DOOM_DESKTOP

mkdir $BRUTAL_DOOM_CONFIG
cp ./banner.jpg $BRUTAL_DOOM_STEAM_BANNER
cp ./logo.png $BRUTAL_DOOM_STEAM_LOGO