DOOM_BABY      : int = 0 
DOOM_EASY      : int = 1
DOOM_MEDIUM    : int = 2
DOOM_HARD      : int = 3
DOOM_NIGHTMARE : int = 4

HERETIC_BABY      : int = 1
HERETIC_EASY      : int = 2 
HERETIC_MEDIUM    : int = 3
HERETIC_HARD      : int = 4
HERETIC_NIGHTMARE : int = 5

HEXEN_BABY      : int = HERETIC_BABY
HEXEN_EASY      : int = HERETIC_EASY 
HEXEN_MEDIUM    : int = HERETIC_MEDIUM
HEXEN_HARD      : int = HERETIC_HARD
HEXEN_NIGHTMARE : int = HERETIC_NIGHTMARE

STRIFE_BABY      : int = HERETIC_BABY
STRIFE_EASY      : int = HERETIC_EASY 
STRIFE_MEDIUM    : int = HERETIC_MEDIUM
STRIFE_HARD      : int = HERETIC_HARD
STRIFE_NIGHTMARE : int = HERETIC_NIGHTMARE 

TRAINING        : int = HERETIC_BABY
ROOKIE          : int = HERETIC_EASY 
VETERAN         : int = HERETIC_MEDIUM
ELITE           : int = HERETIC_HARD
BLOODBATH       : int = HERETIC_NIGHTMARE 

